### ISSUE TITLE
Cloning git-lfs enabled repo in Visual Studio 2017 causes errors

### ISSUE THREAD

**Issue by sramssh** [git-lfs/git-lfs#2604]
Hi,                                                                                                                                                                     
 I have a repo on GitHub Enterprise that is using Git LFS to store large files. I can clone the repo with Source Tree and also using command line commands successfully. But when I clone the repo using VS2017 I keep getting errors (See below). It is unable to download the LFS files. I have aslo installed Git-LFS client that is listed here https://git-lfs.github.com/.

I think this is might be the wrong forum to ask, but checking here if anybody has seen that issue before? Any help is much appreciated

Error: external filter 'git-lfs filter-process' failed
Error encountered while cloning the remote repository: Git failed with a fatal error.
fatal: <filepath>.xlsx: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Thanks!

**Comment by sramssh** [comment]
This seems to be an issue with git lfs authentication. Credentials for lfs are not found, when I clone from Visual Studio. I fixed it by using oauth token in the repo url when cloning in Visual Studio. Is there a better way to save the credentials instead of using the oauth token in the repo url?


ErrorLog:

git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73)
git version 2.12.2.windows.3

$ git-lfs.exe filter-process
Error downloading object: <filpath>.xlsx (823c329): Smudge error: Error downloa
<filepath>.xlsx (823c329ce2d8dfe46f2c03beed53cfd80fc52dab399965e09379ea5f0435e1a8): batch
 credentials for https://github.xxxxx.com/xxxx/myrepo.git/info/lfs not found:
exec: "askpass": executable file not found in %PATH%

Git credentials for https://github.xxxxx.com/xxxx/myrepo.git/info/lfs not found:
exec: "askpass": executable file not found in %PATH%
github.com/git-lfs/git-lfs/errors.New
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:62
github.com/git-lfs/git-lfs/lfsapi.getGitCreds
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:156
github.com/git-lfs/git-lfs/lfsapi.fillGitCreds
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:163
github.com/git-lfs/git-lfs/lfsapi.getCreds
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:116
github.com/git-lfs/git-lfs/lfsapi.(*Client).DoWithAuth
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:39
github.com/git-lfs/git-lfs/lfsapi.(*Client).DoWithAuth
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:58
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:61
github.com/git-lfs/git-lfs/tq.Batch
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:37
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:426
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:348
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2197
batch response
github.com/git-lfs/git-lfs/errors.newWrappedError
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrap
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:74
github.com/git-lfs/git-lfs/tq.(*tqClient).Batch
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:64
github.com/git-lfs/git-lfs/tq.Batch
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/api.go:37
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:426
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:348
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2197
Error downloading <filepath>.xlsx (823c329ce2d8dfe46f2c03beed53cfd80fc52dab39996
5e1a8)
github.com/git-lfs/git-lfs/errors.newWrappedError
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.Wrapf
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/lfs.downloadFile
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:96
github.com/git-lfs/git-lfs/lfs.PointerSmudge
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:61
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:112
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
        C:/Go/src/runtime/proc.go:185
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2197
Smudge error
github.com/git-lfs/git-lfs/errors.newWrappedError
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:170
github.com/git-lfs/git-lfs/errors.NewSmudgeError
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/errors/types.go:256
github.com/git-lfs/git-lfs/lfs.PointerSmudge
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:70
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:128
github.com/git-lfs/git-lfs/commands.filterCommand
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:112
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35
runtime.main
        C:/Go/src/runtime/proc.go:185
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2197

Current time in UTC:
2017-09-22 03:50:41

ENV:
LocalWorkingDir=C:\Users\<XXXX>\Source\Repos\myrepo
LocalGitDir=C:\Users\<XXXX>\Source\Repos\myrepo\.git
LocalGitStorageDir=C:\Users\<XXXX>\Source\Repos\myrepo\.git
LocalMediaDir=C:\Users\<XXXX>\Source\Repos\myrepo\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\<XXXX>\Source\Repos\myrepo\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\<XXXX>\Source\Repos\myrepo\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_ASKPASS=askpass
GIT_CEILING_DIRECTORIES=C:\Users\<XXXX>\Source\Repos
GIT_CONFIG_PARAMETERS='gc.auto=0' 'credential.helper=manager' 'core.askpass=askpass' 'http.extraheader=X-TFS-NoLogo: VS15/15.0.0'
GIT_DIR=.git
GIT_EXEC_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\l
e
GIT_FLUSH=1
GIT_HTTP_USER_AGENT=git/2.12.2 (Microsoft Windows NT 10.0.15063.0; Win32NT x64) CLR/4.0.30319 VS15/15.0.0
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_MERGE_VERBOSITY=4
GIT_PAGER=cat
GIT_TERMINAL_PROMPT=0

**Comment by technoweenie** [comment]
Git LFS v2.3.0 adds `GIT_ASKPASS` functionality. Your git config shows:

> GIT_ASKPASS=askpass
> GIT_CONFIG_PARAMETERS='gc.auto=0' 'credential.helper=manager' 'core.askpass=askpass' 'http.extraheader=X-TFS-NoLogo: VS15/15.0.0'

I see this error in your log:

> exec: "askpass": executable file not found in %PATH%

I think you'll have to update the settings to point to the correct askpass command.

**Comment by technoweenie** [comment]
Hey, I just pushed out a fix for `GIT_ASKPASS` in https://github.com/git-lfs/git-lfs/pull/2607. It won't solve your PATH issue, but it probably won't work after you resolve it. So you may want to roll back to LFS v2.2.x until v2.3.1 is released next week.

**Comment by sramssh** [comment]
I added env variable for GIT_ASKPASS I still get the same error. I'll wait for next week to get the next version. I am good for now.

**Comment by technoweenie** [comment]
My patch won't fix the fact that `askpass` is not in your `%PATH%`. You can try passing an absolute file path to it.

**Comment by technoweenie** [comment]
I just released [LFS v2.3.1](https://github.com/git-lfs/git-lfs/releases/tag/v2.3.1), which fixes `GIT_ASKPASS` support.
