### ISSUE TITLE
git lfs migrate import removes final newline on commit messages

### ISSUE THREAD

**Issue by jcallen-gentoo** [git-lfs/git-lfs#3040]
When running `git lfs migrate import` on , I found that it modified every commit message to remove the final newline character, even if it would not otherwise have modified the commit at all.

A simple reproducer is:

```sh
mkdir test
cd test
git init
git commit --allow-empty -m 'initial commit'
git cat-file -p HEAD
git lfs migrate import
git cat-file -p HEAD
```

Notice that the commit SHA1 for the `master` branch changes, even though the tree, author, and committer have not, and that the `git cat-file -p HEAD` before the import outputs a final newline, but the `git cat-file -p HEAD` after the import does not.

**Comment by ttaylorr** [comment]
Hi @jcallen-gentoo, thanks for opening this issue! I was out of the office last week, so I apologize for the slower response. I think I figured out what was going on and wrote https://github.com/git-lfs/git-lfs/pull/3053 to fix this. Can you give that a shot and see if it works for you?

**Comment by jcallen-gentoo** [comment]
I just checked, and #3053 fixes the commit message changing.  I noticed that it now adds an empty .gitattributes file in the root of the repository on early commits where no file was migrated (an initial empty commit, for instance), but my particular use-case doesn't care (as my real repo has files that need to be migrated in the initial commit).

**Comment by ttaylorr** [comment]
> I noticed that it now adds an empty .gitattributes file in the root of the repository on early commits where no file was migrated (an initial empty commit, for instance), but my particular use-case doesn't care (as my real repo has files that need to be migrated in the initial commit).

Hi again, @jcallen-gentoo -- I fixed this issue in #3054, can you give that a shot as well? Thanks!

**Comment by cnrmck** [comment]
Is this change represented in git-lfs/2.7.2 (GitHub; darwin amd64; go 1.12.4)? 

I'm still seeing this issue

**Comment by bk2204** [comment]
This change should be present in 2.7.2. If you're still seeing it, can you please open a new issue as mentioned in [the contributing guidelines](https://github.com/git-lfs/git-lfs/blob/master/CONTRIBUTING.md#issues)?

**Comment by cnrmck** [comment]
Yes!
