### ISSUE TITLE
No progress output on Windows

### ISSUE THREAD

**Issue by simonm3** [git-lfs/git-lfs#3704]
I am pushing a commit that includes 2GB of files going to git lfs. On git version 2.20 this reports progress

Uploading LFS objects: 8% (5/62), 170 MB | 451 KB/s

On version 2.21 and 2.22 it reports nothing. Even with the -v flag it just says it is pushing. I am not sure if it has just hung or is doing it quietly in the background. Is there any way to see progress for a long running operation like this?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Can you tell me what OS and distribution of Git you're using? Also, how are you invoking this command? Is it a plain `git push`, or are you using `git lfs push` directly?

**Comment by simonm3** [comment]
Windows git push. Version 22.

Possibly issue is I started the push on version 20. Upgraded to speed up.
Then it just hung. Not sure if is progress bar missing or hung.

**Comment by bk2204** [comment]
I think this may be the same issue as #3575, which is now fixed in `master` (but not yet any released version). Can you try building the latest `master` version and see if that works for you?

**Comment by mstrap** [comment]
I can't confirm that this is fixed. One of our user and myself are experiencing this problem now. Tested on Windows with:

```
$ git --version
git version 2.23.0.windows.1

$ git lfs --version
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
```

I have also tried with latest master (b6e27793). When redirecting `stdout` and `stderr`, this is what I see on console (the three username/password prompts are a different issue):

```
D:\gittest\gitlab-lfs>git push > out 2> err
Username for 'https://server': marc
Password for 'https://marc@server':
Username for 'https://server': marc
Password for 'https://marc@server':
Username for 'https://server': marc
Password for 'https://marc@server':
```

`out` file:

```
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://server/internal/test-lfs.git/info/lfs.locksverify true
Uploading LFS objects: 100% (2/2), 21 MB | 621 KB/s, done.
```

`err` file:

```
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
stty: 'standard input': Inappropriate ioctl for device
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
stty: 'standard input': Inappropriate ioctl for device
warning: redirecting to https://server/internal/test-lfs.git/
To https://server/internal/test-lfs
   6a3bb43..4d40661  master -> master
```

**Comment by bk2204** [comment]
You will definitely not see anything on the terminal if you redirect the output, since the progress bar is dependent on the output being a TTY.  What terminal are you using on Windows?  Is it Windows Terminal, the built-in console, Git Bash (MinTTY)?

**Comment by mstrap** [comment]
> You will definitely not see anything on the terminal if you redirect the output, since the progress bar is dependent on the output being a TTY.

Has this been changed recently? According to our user progress used to show up in our application with earlier versions (including older Git and Git-LFS).

Git commands in general output progress to stderr using "Erase in Line" CSI sequence. I think Git-LFS should do the same. Should I open a new topic for this?

**Comment by bk2204** [comment]
Hey,

Is this fixed in the latest version of Git for WIndows?  There was a bug in older versions where the TTY handling was broken.

**Comment by mstrap** [comment]
@bk2204 sorry for the late reply -- I missed your last post. Unfortunately it's not yet fixed:

```
D:\gittest\gitlab.lfs.clone>git --version
git version 2.29.0.windows.1

D:\gittest\gitlab.lfs.clone>git lfs --version
git-lfs/2.12.0 (GitHub; windows amd64; go 1.14.7; git dad7b9e6)

D:\gittest\gitlab.lfs.clone>git push > out 2> err
```
just prints to `out`:

```
Consider unlocking your own locked files: (`git lfs unlock <path>`)
* huge7
Uploading LFS objects: 100% (1/1), 10 MB | 628 KB/s, done.
```

and `err`:

```
To https://marc@server/test-lfs.git
0ace474..6b3b22f  master -> master
```

**Comment by ZimM-LostPolygon** [comment]
Fixed yet?..

**Comment by bk2204** [comment]
Nothing here has changed in Git LFS.  I would say that this looks like a bug in Git for Windows, since the progress output does work when forced on and it does work on Linux.  You'd probably want to talk to the Git for Windows folks about it if you're seeing a problem.

**Comment by ayan4m1** [comment]
Still having this issue, which prevents my CLI utility from parsing progress info for large checkouts. Very painful.

**Comment by havenking** [comment]
I'm having this issue since I turned LFS on due to my Unreal project file sizes. It's very painful when I make big changes in my levels and light scenarios and have to wait a long time without knowing if the upload is working or not.

**Comment by chrisd8088** [comment]
FWIW, I'm unable to replicate this problem on a Windows 11 VM, using the latest Git for Windows release with Git v2.46.0 and Git LFS v3.5.1.  I've put the test steps below and a sample video as well.

One key point to note is that both Git and Git LFS generally avoid outputting a progress meter if they detect they are not writing directly to a terminal, but instead to a file or another process.  So in https://github.com/git-lfs/git-lfs/issues/3704#issuecomment-742814857 above (which is from a few years ago), there's a mention of trying to run `git push >out 2> err` and then not finding progress meter output in the `out` file.  That's normal unless you explicitly force progress meter output while writing to a non-terminal with with the `lfs.forceProgress` Git configuration or the `GIT_LFS_FORCE_PROGRESS=1` environment variable.  See the relevant [section](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/docs/man/git-lfs-config.adoc#L370-L377) in the `git-lfs-config(5)` manual page for more details.

 So in the case of another, more recent [comment](https://github.com/git-lfs/git-lfs/issues/3704#issuecomment-1979844265), if a "CLI utility" is attempting to capture and parse Git LFS progress output, you would need to make sure either the environment variable or Git configuration are enabled for that to work.

Note also that Git has a similar setting, the `--progress` option to `git-push(1)`, as [described](https://git-scm.com/docs/git-push#Documentation/git-push.txt---progress) in the Git documentation.

---

As for a test setup, I used the following to create 1000 Git LFS objects and push them (just to another repository on the same system, but this should apply for any remote):

```
$ git init --bare source
$ git clone source target
$ cd target

$ git lfs track "*.bin"
$ git add .gitattributes
$ git commit -m attrs
$ git push origin main

$ for ((i=0;i<1000;++i)); do
$  f=$(printf "foo%04d.bin" $i)
$  head -c 100K /dev/urandom >"$f"
$ done

$ git add *.bin
$ git commit -m bins

$ git config lfs.forceProgress true

$ git push origin main >../out 2>../err
```

Because I set `lfs.forceProgress=true`, the normal terminal-mode progress meter output and is captured in `out`.  Note that because it uses carriage returns to write over the same line repeatedly, if you just `cat` the file all you see is the final line:

```
$ cat ../out
Uploading LFS objects: 100% (1000/1000), 0 B | 0 B/s, done. 
```

But if you examine the file's full contents, there are multiple lines showing Git LFS's incremental progress, with `\r` separating them:
```
$ wc -c ../out
    2247 out

$ strings ../out
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s                                  
Uploading LFS objects:   0% (0/38), 0 B | 0 B/s                                 
Uploading LFS objects:   0% (0/82), 0 B | 0 B/s                                 
Uploading LFS objects:   0% (0/117), 0 B | 0 B/s                                
Uploading LFS objects:   0% (0/156), 0 B | 0 B/s                                
Uploading LFS objects:   0% (0/190), 0 B | 0 B/s                                
Uploading LFS objects:  23% (52/231), 0 B | 0 B/s                               
Uploading LFS objects:  74% (200/272), 0 B | 0 B/s                              
Uploading LFS objects:  89% (281/314), 0 B | 0 B/s                              
Uploading LFS objects:  83% (300/360), 0 B | 0 B/s                              
Uploading LFS objects:  75% (300/401), 0 B | 0 B/s                              
Uploading LFS objects:  90% (400/446), 0 B | 0 B/s                              
Uploading LFS objects:  82% (400/487), 0 B | 0 B/s                              
Uploading LFS objects:  82% (429/523), 0 B | 0 B/s                              
Uploading LFS objects:  82% (441/539), 0 B | 0 B/s                              
Uploading LFS objects:  81% (450/559), 0 B | 0 B/s                              
Uploading LFS objects:  84% (500/595), 0 B | 0 B/s                              
Uploading LFS objects:  95% (600/631), 0 B | 0 B/s                              
Uploading LFS objects:  90% (600/669), 0 B | 0 B/s                              
Uploading LFS objects:  95% (677/713), 0 B | 0 B/s                              
Uploading LFS objects:  92% (700/758), 0 B | 0 B/s                              
Uploading LFS objects:  88% (701/801), 0 B | 0 B/s                              
Uploading LFS objects:  95% (800/846), 0 B | 0 B/s                              
Uploading LFS objects:  90% (800/890), 0 B | 0 B/s                              
Uploading LFS objects:  97% (900/932), 0 B | 0 B/s                              
Uploading LFS objects:  93% (900/971), 0 B | 0 B/s                              
Uploading LFS objects: 100% (1000/1000), 0 B | 0 B/s                            
Uploading LFS objects: 100% (1000/1000), 0 B | 0 B/s, done.

$ od -vc ../out | head -n 6
0000000    U   p   l   o   a   d   i   n   g       L   F   S       o   b
0000020    j   e   c   t   s   :               0   %       (   0   /   1
0000040    )   ,       0       B       |       0       B   /   s        
0000060                                                                 
0000100                                                                 
0000120   \r   U   p   l   o   a   d   i   n   g       L   F   S       o
```

I recorded a short demo where running `git lfs push origin -all` on this same test repository, to a remote lacking any of the LFS objects, can be seen to be write and rewrite its progress meter.  Note that I removed the `lfs.forceProgress` Git configuration beforehand to illustrate that this works in the normal case where output is directed to a terminal and that setting is not enabled.

https://github.com/user-attachments/assets/3653a615-9d3d-4179-9a27-3c663d70cfee

This was recorded in a Git CMD session; the output is the same in a Git Bash session.

**Comment by ayan4m1** [comment]
> So in the case of another, more recent [comment](https://github.com/git-lfs/git-lfs/issues/3704#issuecomment-1979844265), if a "CLI utility" is attempting to capture and parse Git LFS progress output, you would need to make sure either the environment variable or Git configuration are enabled for that to work.

Really appreciate this info. I should be able to set things up properly in my utility now and force the output when I run git internally.

**Comment by havenking** [comment]
Thank you @chrisd8088 

After using `>git config lfs.forceprogress true` the problem was fixed for me.

**Comment by chrisd8088** [comment]
Based on recent feedback, and as I think we've demonstrated in https://github.com/git-lfs/git-lfs/issues/3704#issuecomment-2295093104 that this is no longer a problem with recent Git and Git LFS versions, I'm going to close this issue.
