### ISSUE TITLE
hooks and lfs folders are created on project root instead of inside .git folder when using git-lfs

### ISSUE THREAD

**Issue by StarWars999123** [git-lfs/git-lfs#3898]
The issue occured after Installation of the latest Git LFS 2.9.0 on a PC with Visual Studio 2019 16.3.6. git-lfs --version from cmd says, it runs with GitLFS version 2.8.0. 

Finally the project root looks like this: 
```
.git/
    hooks/
        pre-push
        post-checkout
        post-merge
        post-commit
hooks/
    pre-push
    post-checkout
    post-merge
    post-commit
ourFilesAndStuff
```
The issue occured already several times on different developer PCs. We are not sure, how we should handle this. A simple delete does not help, as it gets allways recreated immedeatly.

- Does this happen due to a version conflict of the git LFS delivered by VisualStudio or why can it occur?
- Shall we check-in this Hooks-Folder or put it into the .gitignore?
- Whats the reason that it gets created?

**Comment by bk2204** [comment]
Hey,

Can you provide the output of `git config -l` on an affected system?  I think there might be a `core.hooksPath` setting that's causing this.

**Comment by StarWars999123** [comment]
Luckily I have currently a working repository without this anomaly. On this system does git config -l does not list any core.hooksPath. I'll try to install the mentioned lfs version 2.9.0 again in a few days.

**Comment by bk2204** [comment]
It would also be useful to have the output of `git lfs env`.  There were some changes in 2.8.0 that had to do with hooks, and knowing what Git LFS thinks some of those paths are would help troubleshooting.

**Comment by StarWars999123** [comment]
```
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
git version 2.23.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Okay, I think I know what the problem is.

We recently started to use `cygpath` to canonicalize paths on Windows, but apparently you don't have that binary in your PATH.  Consequently, you get an empty string in this case, leading the code to use the current directory.

I'll open a draft PR shortly with a proposed solution.  It would be great if you could download the binary from the CI artifacts once it's built and verify that (a) you're using the new binary and (b) that running `git-lfs env` with the new binary emits correct values for `LocalGitDir` (which should be your `.git` directory) and that `LocalMediaDir` is located underneath it.

**Comment by bk2204** [comment]
I can't reproduce this myself, so without reproduction steps or someone verifying that #3910 works for them, we won't be able to fix this.

**Comment by vbedrosova** [comment]
Hi, guys.
May be related - each time I start git-lfs on windows - there is lfs folder (containing empty objects and tmp folders) is created in the working folder.
Came across this while investigating https://youtrack.jetbrains.com/issue/TW-63074
See "git-lfs" env output below:
D:\TeamCity20192\buildAgent>git-lfs env
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.20.1.vfs.1.1.104.g2ab7360
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = ""
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by Jamy4000** [comment]
@vbedrosova I had the same issue, doing a `git update-git-for-windows` command and deleting the folders fixed the issue for me !

**Comment by bk2204** [comment]
I believe the issue that's present in 2.9.0 and 2.9.1 has been fixed in #3910 and the fix will be included in 2.9.2, due out Thursday, so I'm closing this.

**Comment by janissimsons** [comment]
This is not fixed.
I am running latest git lfs version (v2.13.3) and lfs objects are being created in project root directory.

**Comment by jgwinner** [comment]
I ran into this as well just recently. I'll open a new ticket per the above.
