### ISSUE TITLE
Encountered (N) file(s) that may not have been copied correctly on Windows

### ISSUE THREAD

**Issue by xls** [git-lfs/git-lfs#4744]
**Describe the bug**
with Git-for-windows 2.34.0 the checksum now supports 4GB+ and therefor fixed the smudge with the recent release.

**To Reproduce**
1. Clone a repository with configured lfs
2. Add a +4gb file and commit

4. See warning: 
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        test.bin

nothing added to commit but untracked files present (use "git add" to track)

d:\Github\nexuslfs>git add test.bin
Encountered 1 file(s) that may not have been copied correctly on Windows:
        test.bin

See: `git lfs help smudge` for more details.
```

**Expected behavior**
don't show warning when git.exe is of greater version than 2.34.0

**System environment**
Windows 10 Pro,
git-for-windows 2.34.0.windows.1
.gitconfig = user info only.

**Output of `git lfs env`**

```
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  This has been a thing I've been meaning to get to, but haven't yet, so we are aware of the issue and it's on my list of things to do for 3.1.0.  Since I have some vacation coming up, it may not get done immediately, but rest assured we'll do our very best for 3.1.0.

I will note that there is the slimmest of possibilities that someone is building from the original Git upstream source rather than the Git for Windows source and therefore doesn't have this patch, since it won't be in upstream Git until 2.35, but I think that possibility is unlikely enough that we can ignore it, especially since this is only a warning.

**Comment by Controluser** [comment]
Use git-lfs instead of git
`git-lfs clone https://github.com/your-username/sample-repository.git`

**Comment by unphased** [comment]
I find whenever this output shows up that the .git/lfs dir remains full of content, so the cloned git repo is twice as big as it should be. and I have to manually go in to clean it. I wish that weren't necessary. I will try to remember to use `git-lfs` instead next time to see if that fixes it.

**Comment by VpkPrasanna** [comment]
> Use git-lfs instead of git `git-lfs clone https://github.com/your-username/sample-repository.git` Change to the actual repository. This worked for me

This fixed when i tried to download huge model from huggingface !

**Comment by TomerMassas** [comment]
git-lfs worked for me too

**Comment by chrisd8088** [comment]
@zhanwenchen --

This is quite an old issue, and the original problem has been fixed in Git for Windows 2.34.0 (see PR #4768 for details).  If you are using a version older than that, you should definitely upgrade.

> The `git-lfs` command does work, but it says it is deprecated. Is there another way to make `git clone` work?

This was a workaround until the Git for Windows problem was resolved.  You should just be able to run `git clone` now, so long as you have a recent version of Git for Windows (and Git and Git LFS).

If you still have problems, please open a new issue rather than comment on an old one, and fill out all the requested information such as the output of `git lfs env` and `git config -l` (with any private information removed) so we can better assist you.

**Comment by vadimkantorov** [comment]
I'm still having `git clone` print this warning - surprisingly on a Linux machine:
```
git clone ...
Filtering content: 100% (4/4), 4.87 GiB | 14.86 MiB/s, done.
Encountered 2 file(s) that may not have been copied correctly on Windows:                                                           model-00001-of-00003.safetensors
model-00002-of-00003.safetensors

See: `git lfs help smudge` for more details.
```

```
$ git --version
git version 2.34.1

$ git-lfs --version
git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)
```

**Comment by bk2204** [comment]
The version of Git LFS you're using is too old.  This was fixed in Git LFS 3.1.0.

**Comment by Joe-Hall-Lee** [comment]
> 我仍然`git clone`打印这个警告——令人惊讶的是，这还是在 Ubuntu-22.04 的机器上。难道这个修复没有包含在 Ubuntu-22.04 的发行版中吗？
> 
> ```
> git clone ...
> Filtering content: 100% (4/4), 4.87 GiB | 14.86 MiB/s, done.
> Encountered 2 file(s) that may not have been copied correctly on Windows:
> model-00001-of-00003.safetensors
> model-00002-of-00003.safetensors
> 
> See: `git lfs help smudge` for more details.
> ```
> 
> ```
> $ git --version
> git version 2.34.1
> 
> $ git-lfs --version
> git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)
> ```

I have updated Git LFS version to 3.6.1 but I still have the same problem when using ```git add .```.

**Comment by Joe-Hall-Lee** [comment]
> I'm still having `git clone` print this warning - surprisingly on a Ubuntu-22.04 machine. Did the fix not make it into the release in Ubuntu-22.04?
> 
> ```
> git clone ...
> Filtering content: 100% (4/4), 4.87 GiB | 14.86 MiB/s, done.
> Encountered 2 file(s) that may not have been copied correctly on Windows:
> model-00001-of-00003.safetensors
> model-00002-of-00003.safetensors
> 
> See: `git lfs help smudge` for more details.
> ```
> 
> ```
> $ git --version
> git version 2.34.1
> 
> $ git-lfs --version
> git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)
> ```

I have updated Git LFS version to 3.6.1 but I still have the same problem when using ```git add .```.

**Comment by chrisd8088** [comment]
> I have updated Git LFS version to 3.6.1 but I still have the same problem when using `git add .`.

@Joe-Hall-Lee — You don't indicate what version of Git (not Git LFS) you are using, but I imagine it is earlier than Git v2.34.0, because that is what is now [required](https://github.com/git-lfs/git-lfs/blob/d5db3c873ed3cf90b667d796a2c39b0dc7674578/commands/command_filter_process.go#L229) in order for the warning to be output.

If you upgrade your Git version and still see the warning message, then as we've noted [before](https://github.com/git-lfs/git-lfs/issues/4744#issuecomment-2183276591) in this issue, please open a fresh issue and fill out all the details we request, including, if at all possible, a full reproduction case.
